language: ruby
rvm:
    - 2.3.3


install:
    - gem install jekyll

script:
    - jekyll build
    - echo "archive.discordspark.tk" > ./_site/CNAME

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true

branches:
  except:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

notifications:
  webhooks:
    urls:
      - https://travis---discord-webhook-gk6taungzyj7.runkit.sh/
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
